import { PromptDefinition } from '../types.js';

export const metroManilaCity: PromptDefinition = {
  id: 'metro-manila-city',
  category: 'City in Metro Manila',
  promptText: 'Name a city in Metro Manila.',
  canonicalAnswers: [
    'Caloocan',
    'Las Piñas',
    'Makati',
    'Malabon',
    'Mandaluyong',
    'Manila',
    'Marikina',
    'Muntinlupa',
    'Navotas',
    'Parañaque',
    'Pasay',
    'Pasig',
    'Quezon City',
    'San Juan',
    'Taguig',
    'Valenzuela',
  ],
  aliases: {
    QC: 'Quezon City',
    'Q.C.': 'Quezon City',
    'Las Pinas': 'Las Piñas',
    Paranaque: 'Parañaque',
    // Most of these cities are also commonly called "<Name> City" (Quezon City already has
    // "City" baked into its canonical name, so it needs no alias here).
    'Caloocan City': 'Caloocan',
    'Las Piñas City': 'Las Piñas',
    'Makati City': 'Makati',
    'Malabon City': 'Malabon',
    'Mandaluyong City': 'Mandaluyong',
    'Manila City': 'Manila',
    'Marikina City': 'Marikina',
    'Muntinlupa City': 'Muntinlupa',
    'Navotas City': 'Navotas',
    'Parañaque City': 'Parañaque',
    'Pasay City': 'Pasay',
    'Pasig City': 'Pasig',
    'San Juan City': 'San Juan',
    'Taguig City': 'Taguig',
    'Valenzuela City': 'Valenzuela',
  },
  // Pateros is a municipality, not a city; Metro Manila/NCR are the region itself, not a city within it.
  rejections: ['Pateros', 'Metro Manila', 'NCR'],
  hostAnswer: 'Quezon City',
};
