import { PromptDefinition } from '../types.js';

export const phRegion: PromptDefinition = {
  id: 'ph-region',
  category: 'Region of the Philippines',
  promptText: 'Name a region of the Philippines.',
  canonicalAnswers: [
    'NCR',
    'CAR',
    'Ilocos Region',
    'Cagayan Valley',
    'Central Luzon',
    'CALABARZON',
    'MIMAROPA',
    'Bicol Region',
    'Western Visayas',
    'Central Visayas',
    'Eastern Visayas',
    'Zamboanga Peninsula',
    'Northern Mindanao',
    'Davao Region',
    'SOCCSKSARGEN',
    'Caraga',
    'BARMM',
  ],
  aliases: {
    'Metro Manila': 'NCR',
    'National Capital Region': 'NCR',
    Cordillera: 'CAR',
    'Cordillera Administrative Region': 'CAR',
    'Region 1': 'Ilocos Region',
    'Region I': 'Ilocos Region',
    'Region 2': 'Cagayan Valley',
    'Region II': 'Cagayan Valley',
    'Region 3': 'Central Luzon',
    'Region III': 'Central Luzon',
    'Region 4-A': 'CALABARZON',
    'Region IV-A': 'CALABARZON',
    'Region 4A': 'CALABARZON',
    'Region IVA': 'CALABARZON',
    'Region 4-B': 'MIMAROPA',
    'Region IV-B': 'MIMAROPA',
    'Region 4B': 'MIMAROPA',
    'Region IVB': 'MIMAROPA',
    Bicol: 'Bicol Region',
    'Region 5': 'Bicol Region',
    'Region V': 'Bicol Region',
    'Region 6': 'Western Visayas',
    'Region VI': 'Western Visayas',
    'Region 7': 'Central Visayas',
    'Region VII': 'Central Visayas',
    'Region 8': 'Eastern Visayas',
    'Region VIII': 'Eastern Visayas',
    'Region 9': 'Zamboanga Peninsula',
    'Region IX': 'Zamboanga Peninsula',
    'Region 10': 'Northern Mindanao',
    'Region X': 'Northern Mindanao',
    Davao: 'Davao Region',
    'Region 11': 'Davao Region',
    'Region XI': 'Davao Region',
    'Region 12': 'SOCCSKSARGEN',
    'Region XII': 'SOCCSKSARGEN',
    'Region 13': 'Caraga',
    'Region XIII': 'Caraga',
    Bangsamoro: 'BARMM',
    'Bangsamoro Autonomous Region in Muslim Mindanao': 'BARMM',
    // ARMM was replaced by BARMM in 2019; still commonly used from muscle memory.
    ARMM: 'BARMM',
    // NOTE: bare "Region 4"/"Region IV" is deliberately NOT aliased — it's ambiguous between
    // IV-A (CALABARZON) and IV-B (MIMAROPA), same judgment call as "Maguindanao" in ph-province.ts.
  },
  hostAnswer: 'Central Luzon',
};
